Add Acala and Bitcoin fork chains
trustwallet/assets pull request #25623
Opened 2023-07-01 10:23 UTC by cryptomanz1

2023-07-03 08:45 UTC, satoshiotomakan requested changes
Missing blockchains: [Komodo](https://github.com/trustwallet/wallet-core/blob/master/registry.json#L1209), [IOST](https://github.com/trustwallet/wallet-core/blob/master/registry.json#L3487)

2023-07-03 08:45 UTC, satoshiotomakan commented on blockchains/verge/info/info.json
> +    "decimals": 8,
Verge seems to have 6 decimals: https://github.com/vergecurrency/verge/blob/b9a3f7278ba9c71e993decf38e5fcf731feb8c1d/src/qt/vergeunits.cpp#L89
https://github.com/trustwallet/wallet-core/blob/4443c337f6337aa7fcb76bceb3987ad6a1fbbaf2/registry.json#L444

2023-07-03 08:52 UTC, satoshiotomakan commented
Do we need to add [Scroll](https://github.com/trustwallet/wallet-core/pull/3179), [Conflux eSpace](https://github.com/trustwallet/wallet-core/pull/3259) too?

2023-07-03 09:01 UTC, Milerius commented
> Do we need to add [Scroll](https://github.com/trustwallet/wallet-core/pull/3179), [Conflux eSpace](https://github.com/trustwallet/wallet-core/pull/3259) too? cc: @cryptomanz1 @Milerius

Yes

2023-07-04 07:16 UTC, satoshiotomakan approved these changes
Thank you for the changes! LGTM

2023-07-04 09:11 UTC, merged

2024-03-05 21:12 UTC, Setarland commented
Blakchin