VIDTC NFT's for Binance Smart Chain (3 addresses)
trustwallet/assets pull request #4462
Opened 2020-10-16 11:41 UTC by Sjazzz

Added the info and logo's for Binance Smart Chain NFT's following the ERC721 standard.

Thanks again team TrustWallet!

2020-10-19 05:31 UTC, Iamdeadlyz requested changes

2020-10-19 05:31 UTC, Iamdeadlyz commented on blockchains/smartchain/assets/0x0567D7fad179dCd2a89508B77cCe93E26f8998F7/info.json
> +    "explorer": "https://bscscan.com/address/0x0567d7fad179dcd2a89508b77cce93e26f8998f7"
Please update it to `https://bscscan.com/token/0x0567d7fad179dcd2a89508b77cce93e26f8998f7`

2020-10-19 05:31 UTC, Iamdeadlyz commented on blockchains/smartchain/assets/0x7A2172F3728962F6B952a1Cc1AD794DACbf9f3DA/info.json
> +    "explorer": "https://bscscan.com/address/0x7a2172f3728962f6b952a1cc1ad794dacbf9f3da"
Update this as well to `https://bscscan.com/token/0x7a2172f3728962f6b952a1cc1ad794dacbf9f3da`

2020-10-19 05:31 UTC, Iamdeadlyz commented on blockchains/smartchain/assets/0x7B7D3B71A12906270b1b4c187C75f45188E9aEf6/info.json
> +    "explorer": "https://bscscan.com/address/0x7b7d3b71a12906270b1b4c187c75f45188e9aef6"
This one as well to `https://bscscan.com/token/0x7b7d3b71a12906270b1b4c187c75f45188e9aef6`

2020-10-20 15:08 UTC, catenocrypt commented
These All these 3 tokens have very low circulation on BSC, a min. of 500 holders is the limit for inclusion.
Are these tokens active on other chain as well (like eth)?

2020-10-20 16:01 UTC, Sjazzz commented
> These All these 3 tokens have very low circulation on BSC, a min. of 500 holders is the limit for inclusion.
> Are these tokens active on other chain as well (like eth)?

Hi, these are new NFT contracts that will connect to the VIDT Datalink contracts at ...
https://etherscan.io/token/0xfeF4185594457050cC9c23980d301908FE057Bb1
and
https://bscscan.com/token/0x3f515f0a8e93f2e2f891ceeb3db4e62e202d7110

Currently there are about 5,300 holders.

Thanks again!

2020-10-21 09:03 UTC, Iamdeadlyz approved these changes

2020-10-21 09:04 UTC, merged