Fix ethereum addres in tokenlist
trustwallet/assets pull request #4474
Opened 2020-10-17 01:03 UTC by leoneparise

2020-10-17 01:18 UTC, vikmeup approved these changes

2020-10-19 09:28 UTC, catenocrypt approved these changes
Isn't tokenlist.json generated?  Will this change not be overwritten with next update?

2020-11-05 07:55 UTC, vudu0602 requested changes

2020-11-05 07:55 UTC, vudu0602 commented on blockchains/ethereum/tokenlist.json
> -         "asset":"c60",
https://trustwallet.com/assets/images/favicon.png

2020-11-05 07:56 UTC, vudu0602 requested changes

2020-11-05 07:56 UTC, vudu0602 commented on blockchains/ethereum/tokenlist.json
> -         "asset":"c60",
leoneparise:leone/tokenlist-fix

2020-11-05 09:14 UTC, closed without merging