Add mUSDK and mUSDT
trustwallet/assets pull request #5114
Opened 2020-12-16 21:00 UTC by coreycaplan3

2020-12-17 08:50 UTC, catenocrypt commented
Please add an `info.json` files, one next to each `logo.png` file, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

2020-12-18 04:34 UTC, coreycaplan3 commented
Just updated the PR with the requested changes!

2020-12-18 10:44 UTC, catenocrypt commented
1., Can you please fix the website -- double com at the end   "website": "https://defimoneymarket.com.com",
2.,  These wrapped tokens have very low circulations.  Could you share some link about DMM numbers?  (liquidity, volume, ...)

2020-12-28 03:05 UTC, vikmeup reviewed
Can you fix CI and should be good to merge

2020-12-28 03:05 UTC, vikmeup commented on blockchains/ethereum/allowlist.json
> +    "0x413237cf1b1Ee88e551b5ad1DC117aBF1004F9eA",
can you remove from this link? it's generated automatically

2020-12-29 17:31 UTC, Iamdeadlyz requested changes

2020-12-29 17:31 UTC, Iamdeadlyz commented on blockchains/ethereum/assets/0xD1670Cb7c01987a8DdD6976C4894463460Eeb8a2/info.json
> +    "website": "https://defimoneymarket.com.com",
Please change `https://defimoneymarket.com.com` to `https://defimoneymarket.com`

2020-12-29 17:31 UTC, Iamdeadlyz commented on blockchains/ethereum/assets/0x84d4AfE150dA7Ea1165B9e45Ff8Ee4798d7C38DA/info.json
> +    "website": "https://defimoneymarket.com.com",
Please change `https://defimoneymarket.com.com` to `https://defimoneymarket.com`

2021-01-04 21:27 UTC, coreycaplan3 commented
The stats for our overall usage can be found here:
https://app.defimoneymarket.com/
https://defimarketcap.io/protocol/dmm

We have pull requests open for them to track more wrapped tokens. The two we added have a 6-figure market cap.

2021-01-07 05:49 UTC, Iamdeadlyz approved these changes

2021-01-07 05:50 UTC, merged